---
- name: Create app group
  become: true
  ansible.builtin.group:
    name: app
- name: Create app user
  become: true
  ansible.builtin.user:
    name: app
    group: app
- name: Configure nginx repository file
  become: true
  ansible.builtin.copy:
    src: "nginx.repo"
    dest: "/etc/yum.repos.d/nginx.repo"
    mode: "0644"
    owner: "root"
    group: "root"
- name: Install dependences packages
  become: true
  ansible.builtin.yum:
    name:
      - git
      - nginx
    state: present
  # notify: Start nginx service
- name: Clone Lighthouse sources
  become: true
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: /usr/share/nginx/lighthouse
    single_branch: true
    version: master
- name: Configure NGINX for Lighthouse
  become: true
  ansible.builtin.copy:
    src: "lighthouse.conf"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: Start nginx service
